"""Export block diagrams as Xpedition netlist seed scripts or CSV."""
from typing import List


def generate_netlist_csv(diagram: dict) -> str:
    """Generate a CSV netlist seed from a block diagram.

    Columns: Instance, Part_Number, Pin, Net, Net_Class
    """
    lines = ["Instance,Part_Number,Pin,Net,Net_Class"]

    # Build a quick lookup: (block_id, port_id) -> (block, port)
    blocks_by_id = {b["id"]: b for b in diagram.get("blocks", [])}

    for conn in diagram.get("connections", []):
        src_block = blocks_by_id.get(conn["source_block_id"], {})
        tgt_block = blocks_by_id.get(conn["target_block_id"], {})
        signal = conn.get("signal_name") or "UNNAMED"
        net_class = conn.get("net_class") or ""

        src_port_label = _find_port_label(src_block, conn["source_port_id"])
        tgt_port_label = _find_port_label(tgt_block, conn["target_port_id"])

        lines.append(
            f"{src_block.get('label', '?')},{src_block.get('part_number', '')},"
            f"{src_port_label},{signal},{net_class}"
        )
        lines.append(
            f"{tgt_block.get('label', '?')},{tgt_block.get('part_number', '')},"
            f"{tgt_port_label},{signal},{net_class}"
        )

    return "\n".join(lines)


def generate_netlist_script(diagram: dict) -> str:
    """Generate a Python script that seeds Xpedition ViewDraw with component instances and nets."""
    blocks = diagram.get("blocks", [])
    connections = diagram.get("connections", [])
    blocks_by_id = {b["id"]: b for b in blocks}

    # Build component list
    comp_rows = []
    for b in blocks:
        comp_rows.append(
            f'    {{"instance": {_q(b["label"])}, "part_number": {_q(b.get("part_number"))}, '
            f'"category": {_q(b.get("category", "Custom"))}}}'
        )
    comp_literal = "[\n" + ",\n".join(comp_rows) + "\n]" if comp_rows else "[]"

    # Build net list
    net_rows = []
    for c in connections:
        src = blocks_by_id.get(c["source_block_id"], {})
        tgt = blocks_by_id.get(c["target_block_id"], {})
        src_port = _find_port_label(src, c["source_port_id"])
        tgt_port = _find_port_label(tgt, c["target_port_id"])
        net_rows.append(
            f'    {{"net": {_q(c.get("signal_name") or "UNNAMED")}, '
            f'"src_inst": {_q(src.get("label", "?"))}, "src_pin": {_q(src_port)}, '
            f'"tgt_inst": {_q(tgt.get("label", "?"))}, "tgt_pin": {_q(tgt_port)}, '
            f'"net_class": {_q(c.get("net_class"))}}}'
        )
    net_literal = "[\n" + ",\n".join(net_rows) + "\n]" if net_rows else "[]"

    return f'''#!/usr/bin/env python
"""Xpedition ViewDraw — Netlist Seed Script
Auto-generated by the GDMS Space Hardware Assistant (Block Diagram Builder).

This script connects to Xpedition Designer via COM and creates component
instances and net stubs based on the block diagram.

Usage:
    1. Open the target design in Xpedition Designer.
    2. Run: python xpedition_netlist_seed.py
"""
import sys

COMPONENTS = {comp_literal}

NETS = {net_literal}


def main():
    try:
        import win32com.client
    except ImportError:
        print("ERROR: pywin32 is not installed.")
        print("Install it with:  pip install pywin32")
        sys.exit(1)

    print("GDMS Space Hardware Assistant — Xpedition Netlist Seed Script")
    print(f"Components: {{len(COMPONENTS)}}, Nets: {{len(NETS)}}")
    print("-" * 60)

    try:
        vdapp = win32com.client.Dispatch("ViewDraw.Application")
        print("SUCCESS: Connected to Xpedition Designer")
    except Exception as e:
        print(f"ERROR: Could not connect to Xpedition Designer: {{e}}")
        sys.exit(1)

    # --- Place components ---
    for comp in COMPONENTS:
        inst = comp["instance"]
        pn = comp["part_number"] or "UNKNOWN"
        print(f"  [STUB] Would place {{inst}} ({{pn}})")

    # --- Create nets ---
    for net in NETS:
        name = net["net"]
        src = f"{{net['src_inst']}}.{{net['src_pin']}}"
        tgt = f"{{net['tgt_inst']}}.{{net['tgt_pin']}}"
        print(f"  [STUB] Would create net {{name}}: {{src}} -> {{tgt}}")

    print("\\nDone.")


if __name__ == "__main__":
    main()
'''


def _find_port_label(block: dict, port_id: str) -> str:
    for p in block.get("ports", []):
        if p.get("id") == port_id:
            return p.get("label", port_id)
    return port_id


def _q(value) -> str:
    if value is None:
        return "None"
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
