"""BOM report export generators (Phase 6).

Generates:
- Annotated BOM CSV — original BOM + analysis columns
- Risk summary Markdown report
"""
import csv
import io
from typing import List

from models.bom import BOMReport, BOMAnalysisResult, BOMSummary


def generate_annotated_csv(report: BOMReport) -> str:
    """Generate an annotated BOM CSV with analysis columns appended."""
    output = io.StringIO()
    writer = csv.writer(output)

    # Header
    writer.writerow([
        "Ref Des", "Part Number", "Manufacturer", "Description",
        "Quantity", "Value", "Package", "DNP",
        "Library Match", "Lifecycle", "Radiation Grade",
        "Risk Level", "Risk Flags", "Alternate Parts", "AI Assessment",
    ])

    for r in report.results:
        li = r.line_item
        alt_str = "; ".join(
            f"{a.part_number} ({a.manufacturer})" for a in r.alt_parts
        ) if r.alt_parts else ""
        flags_str = "; ".join(r.risk_flags) if r.risk_flags else ""

        writer.writerow([
            li.ref_des, li.part_number, li.manufacturer, li.description,
            li.quantity, li.value or "", li.package or "",
            "Yes" if li.dnp else "No",
            "Yes" if r.library_match else "No",
            r.lifecycle_status.value,
            r.radiation_grade.value,
            r.risk_level.value,
            flags_str,
            alt_str,
            r.ai_assessment or "",
        ])

    return output.getvalue()


def generate_risk_summary(report: BOMReport) -> str:
    """Generate a Markdown risk summary report."""
    s = report.summary
    lines = [
        f"# BOM Risk Analysis Report",
        f"",
        f"**File:** {report.filename}",
        f"**Generated by:** GDMS Space Hardware Assistant — BOM Analyzer",
        f"",
        f"---",
        f"",
        f"## Summary",
        f"",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Total Line Items | {s.total_line_items} |",
        f"| Unique Part Numbers | {s.unique_parts} |",
        f"| Total Placements | {s.total_placements} |",
        f"| Library Coverage | {s.library_matched}/{s.total_line_items} ({s.library_matched_pct}%) |",
        f"",
        f"## Lifecycle Health",
        f"",
        f"| Status | Count |",
        f"|---|---|",
        f"| ✅ Active | {s.lifecycle_active} |",
        f"| ⚠️ NRND | {s.lifecycle_nrnd} |",
        f"| 🔴 Obsolete | {s.lifecycle_obsolete} |",
        f"| ❓ Unknown | {s.lifecycle_unknown} |",
        f"",
        f"## Radiation Profile",
        f"",
        f"| Grade | Count |",
        f"|---|---|",
        f"| RadHard | {s.rad_hard} |",
        f"| RadTolerant | {s.rad_tolerant} |",
        f"| MIL | {s.rad_mil} |",
        f"| Commercial | {s.rad_commercial} |",
        f"| Unknown | {s.rad_unknown} |",
        f"",
        f"## Risk Distribution",
        f"",
        f"| Level | Count |",
        f"|---|---|",
        f"| 🔴 Critical | {s.risk_critical} |",
        f"| 🟠 High | {s.risk_high} |",
        f"| 🟡 Medium | {s.risk_medium} |",
        f"| 🟢 Low | {s.risk_low} |",
        f"",
    ]

    # Top risk items
    critical_high = [
        r for r in report.results
        if r.risk_level.value in ("Critical", "High")
    ]
    if critical_high:
        lines.extend([
            f"## Top Risk Items",
            f"",
            f"| Ref Des | Part Number | Risk | Flags |",
            f"|---|---|---|---|",
        ])
        for r in critical_high[:20]:
            flags = "; ".join(r.risk_flags[:3]) if r.risk_flags else "—"
            lines.append(
                f"| {r.line_item.ref_des} | {r.line_item.part_number} | "
                f"**{r.risk_level.value}** | {flags} |"
            )
        lines.append("")

    # Alternates section
    with_alts = [r for r in report.results if r.alt_parts]
    if with_alts:
        lines.extend([
            f"## Suggested Alternates",
            f"",
            f"| Part Number | Alternate | Manufacturer | Notes |",
            f"|---|---|---|---|",
        ])
        for r in with_alts[:20]:
            for alt in r.alt_parts[:2]:
                lines.append(
                    f"| {r.line_item.part_number} | {alt.part_number} | "
                    f"{alt.manufacturer} | {alt.notes} |"
                )
        lines.append("")

    lines.extend([
        f"---",
        f"",
        f"*Report generated by GDMS Space Hardware Assistant*",
    ])

    return "\n".join(lines)
