"""Export utilities for COM Channel Analysis (Phase 5).

Generates:
- CES constraint snippet (.py) derived from channel model
- HyperLynx channel model (.csv) for LineSim/BoardSim import
- Summary report (.md) with pass/fail and recommendations
"""
from models.com_channel import ChannelModel, COMResult


# ---------------------------------------------------------------------------
# CES constraint script
# ---------------------------------------------------------------------------

def generate_channel_ces_script(channel: ChannelModel, result: COMResult) -> str:
    """Build a Python script that pushes channel-derived constraints to CES."""
    segments_literal = _build_segments_literal(channel)
    return f'''#!/usr/bin/env python
"""Xpedition CES — Channel Constraint Push Script
Auto-generated by the GDMS Space Hardware Assistant (COM Channel Analysis).

Channel: {channel.name}
Data rate: {channel.data_rate_gbps} Gbps  Modulation: {channel.modulation.value}
Estimated COM: {result.com_db} dB  ({"PASS" if result.passed else "FAIL"})

Usage:
    1. Open the target design in Xpedition Designer.
    2. Run: python xpedition_channel_ces.py
"""
import sys

CHANNEL_NAME = "{channel.name}"
DATA_RATE_GBPS = {channel.data_rate_gbps}
MODULATION = "{channel.modulation.value}"
IMPEDANCE_OHM = {channel.segments[0].impedance_ohm if channel.segments else 100.0}

SEGMENTS = {segments_literal}

# Derived constraints
MAX_TRACE_LENGTH_MM = {_max_trace_length(channel)}
SPACING_RULE_MIL = {_spacing_rule(channel)}

def main():
    try:
        import win32com.client
    except ImportError:
        print("ERROR: pywin32 is not installed.")
        print("Install it with:  pip install pywin32")
        sys.exit(1)

    print("GDMS Space Hardware Assistant — Channel CES Script")
    print(f"Channel: {{CHANNEL_NAME}}")
    print(f"Data rate: {{DATA_RATE_GBPS}} Gbps ({{MODULATION}})")
    print("-" * 60)

    try:
        vdapp = win32com.client.Dispatch("ViewDraw.Application")
        print("SUCCESS: Connected to Xpedition Designer")
    except Exception as e:
        print(f"ERROR: Could not connect to Xpedition Designer: {{e}}")
        sys.exit(1)

    constraints = [
        ("Electrical.Impedance", f"{{IMPEDANCE_OHM}} ohm +/- 10%"),
        ("Physical.MaxLength", f"{{MAX_TRACE_LENGTH_MM}} mm"),
        ("Physical.Spacing", f"{{SPACING_RULE_MIL}} mil min"),
    ]

    for category, value in constraints:
        print(f"  [STUB] Set {{category}} = {{value}} on class '{{CHANNEL_NAME}}'")

    print("\\nDone.")

if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# HyperLynx channel model CSV
# ---------------------------------------------------------------------------

def generate_hyperlynx_csv(channel: ChannelModel) -> str:
    """Build a CSV for HyperLynx LineSim/BoardSim import."""
    lines = [
        "# HyperLynx Channel Model — Auto-generated by GDMS Space Hardware Assistant",
        f"# Channel: {channel.name}",
        f"# Data rate: {channel.data_rate_gbps} Gbps  Modulation: {channel.modulation.value}",
        "",
        "Segment_Label,Segment_Type,Length_mm,Impedance_Ohm,Loss_dB_per_inch,Dk,Df",
    ]
    for seg in channel.segments:
        lines.append(
            f"{seg.label},{seg.type.value},{seg.length_mm},{seg.impedance_ohm},"
            f"{seg.loss_db_per_inch},{seg.dielectric_constant},{seg.loss_tangent}"
        )

    lines.append("")
    lines.append("# TX Parameters")
    lines.append(f"TX_Swing_mV,{channel.tx_params.swing_mv}")
    lines.append(f"TX_DeEmphasis_dB,{channel.tx_params.de_emphasis_db}")
    lines.append(f"TX_PreCursor_Taps,{channel.tx_params.pre_cursor_taps}")

    lines.append("")
    lines.append("# RX Parameters")
    lines.append(f"RX_CTLE_Peaking_dB,{channel.rx_params.ctle_peaking_db}")
    lines.append(f"RX_DFE_Taps,{channel.rx_params.dfe_taps}")
    lines.append(f"RX_DFE_Tap1_mV,{channel.rx_params.dfe_tap1_mv}")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Summary report (Markdown)
# ---------------------------------------------------------------------------

def generate_summary_report(channel: ChannelModel, result: COMResult) -> str:
    """Build a human-readable Markdown summary report."""
    status = "✅ PASS" if result.passed else "❌ FAIL"
    lines = [
        f"# COM Channel Analysis Report",
        f"",
        f"**Channel:** {channel.name}  ",
        f"**Data Rate:** {channel.data_rate_gbps} Gbps  ",
        f"**Modulation:** {channel.modulation.value}  ",
        f"",
        f"## Result",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| **COM** | **{result.com_db} dB** {status} |",
        f"| Eye Height | {result.eye_height_mv} mV |",
        f"| Eye Width | {result.eye_width_ps} ps |",
        f"| Insertion Loss @ Nyquist | {result.total_il_db} dB |",
        f"| Return Loss (worst) | {result.rl_db} dB |",
        f"",
        f"## Channel Segments",
        f"",
        f"| # | Label | Type | Length (mm) | Z (Ω) | Loss (dB/in) |",
        f"|---|-------|------|-------------|--------|--------------|",
    ]

    for i, seg in enumerate(channel.segments, 1):
        lines.append(
            f"| {i} | {seg.label} | {seg.type.value} | {seg.length_mm} | "
            f"{seg.impedance_ohm} | {seg.loss_db_per_inch} |"
        )

    lines.append("")
    lines.append("## TX / RX Equalization")
    lines.append("")
    lines.append(f"- TX Swing: {channel.tx_params.swing_mv} mV")
    lines.append(f"- TX De-emphasis: {channel.tx_params.de_emphasis_db} dB")
    lines.append(f"- RX CTLE Peaking: {channel.rx_params.ctle_peaking_db} dB")
    lines.append(f"- RX DFE Taps: {channel.rx_params.dfe_taps} (tap1 = {channel.rx_params.dfe_tap1_mv} mV)")

    if result.warnings:
        lines.append("")
        lines.append("## Warnings")
        lines.append("")
        for w in result.warnings:
            lines.append(f"- ⚠️ {w}")

    lines.append("")
    lines.append("---")
    lines.append("*Estimated COM — verify in HyperLynx for final signoff.*")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_segments_literal(channel: ChannelModel) -> str:
    rows = []
    for seg in channel.segments:
        rows.append(
            f'    {{"label": "{seg.label}", "type": "{seg.type.value}", '
            f'"length_mm": {seg.length_mm}, "impedance_ohm": {seg.impedance_ohm}, '
            f'"loss_db_per_inch": {seg.loss_db_per_inch}}}'
        )
    return "[\n" + ",\n".join(rows) + "\n]" if rows else "[]"


def _max_trace_length(channel: ChannelModel) -> float:
    """Sum all PCB trace segment lengths."""
    return round(
        sum(s.length_mm for s in channel.segments if s.type.value == "PCB_trace"),
        1,
    )


def _spacing_rule(channel: ChannelModel) -> float:
    """Derive minimum spacing rule in mils based on data rate."""
    if channel.data_rate_gbps >= 25:
        return 8.0
    elif channel.data_rate_gbps >= 10:
        return 5.0
    else:
        return 4.0
