"""Generate a Python script that updates FPGA pin assignments in Xpedition Designer.

The generated script uses win32com.client to connect to a running instance of
ViewDraw.Application and update the pin properties for each swapped signal.
This script is intended to be downloaded and executed locally on the Xpedition machine.
"""
from typing import List


def generate_io_update_script(swapped_pins: List[dict]) -> str:
    """Build a self-contained Python script string for Xpedition I/O Designer updates.

    Args:
        swapped_pins: List of pin swap dicts with keys Signal_Name, Old_Pin,
                      New_Pin, Old_Bank, New_Bank, AI_Risk_Assessment.

    Returns:
        A complete Python script as a string, ready to be saved and executed.
    """
    # Build the swap table as an embedded Python literal
    swap_rows = []
    for s in swapped_pins:
        swap_rows.append(
            f'    {{"Signal_Name": {_q(s["Signal_Name"])}, '
            f'"Old_Pin": {_q(s["Old_Pin"])}, '
            f'"New_Pin": {_q(s["New_Pin"])}, '
            f'"Old_Bank": {_q(s["Old_Bank"])}, '
            f'"New_Bank": {_q(s["New_Bank"])}, '
            f'"AI_Risk_Assessment": {_q(s.get("AI_Risk_Assessment"))}}}'
        )
    swaps_literal = "[\n" + ",\n".join(swap_rows) + "\n]"

    return f'''#!/usr/bin/env python
"""Xpedition I/O Designer — Pin Update Script
Auto-generated by the GDMS Space Hardware Assistant.

This script connects to a running Xpedition Designer instance via COM and
updates FPGA pin assignments based on a Vivado-to-Xpedition delta analysis.

Usage:
    1. Open the target schematic in Xpedition Designer.
    2. Run this script from a Python environment with pywin32 installed:
       python xpedition_pin_update.py
"""
import json
import sys

# ---------------------------------------------------------------------------
# Pin swap data (auto-generated)
# ---------------------------------------------------------------------------
SWAPPED_PINS = {swaps_literal}


def main():
    try:
        import win32com.client
    except ImportError:
        print("ERROR: pywin32 is not installed.")
        print("Install it with:  pip install pywin32")
        sys.exit(1)

    print(f"GDMS Space Hardware Assistant — Xpedition Pin Update Script")
    print(f"Total pin swaps to apply: {{len(SWAPPED_PINS)}}")
    print("-" * 60)

    # --- Connect to Xpedition Designer ---
    try:
        vdapp = win32com.client.Dispatch("ViewDraw.Application")
        print("SUCCESS: Connected to Xpedition Designer (ViewDraw.Application)")
    except Exception as e:
        print(f"ERROR: Could not connect to Xpedition Designer: {{e}}")
        print("Make sure the application is running with a project open.")
        sys.exit(1)

    # --- Apply pin updates ---
    applied = 0
    skipped = 0
    for swap in SWAPPED_PINS:
        signal = swap["Signal_Name"]
        new_pin = swap["New_Pin"]
        new_bank = swap["New_Bank"]
        risk = swap.get("AI_Risk_Assessment", "N/A")

        old_pin = swap["Old_Pin"]
        old_bank = swap["Old_Bank"]
        print(f"\\n  Signal: {{signal}}")
        print(f"    {{old_pin}}/Bank{{old_bank}} -> {{new_pin}}/Bank{{new_bank}}")
        print(f"    Risk: {{risk}}")

        try:
            # TODO: Replace with actual Xpedition I/O Designer API calls.
            # Example pattern (project-specific):
            #   comp = vdapp.GetProjectData().GetComponent(signal)
            #   comp.SetPinProperty("Pin", new_pin)
            #   comp.SetPinProperty("Bank", new_bank)
            print(f"    [STUB] Would update {{signal}} pin to {{new_pin}}, bank to {{new_bank}}")
            applied += 1
        except Exception as e:
            print(f"    [SKIP] Failed to update {{signal}}: {{e}}")
            skipped += 1

    print("\\n" + "=" * 60)
    print(f"Done. Applied: {{applied}}, Skipped: {{skipped}}")


if __name__ == "__main__":
    main()
'''


def _q(value) -> str:
    """Quote a string for embedding in Python source, or return None literal."""
    if value is None:
        return "None"
    # Escape backslashes and quotes for safe embedding
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
