"""Generate a Python script that pushes SI/PI constraints into Xpedition CES.

The generated script uses win32com.client to connect to a running instance of
ViewDraw.Application and apply constraint rules to the Constraint Editor System.
This script is intended to be downloaded and executed locally on the Xpedition machine.
"""
from typing import List


def generate_ces_script(constraints: List[dict]) -> str:
    """Build a self-contained Python script string for Xpedition CES updates.

    Args:
        constraints: List of constraint dicts with keys Signal_Class, Rule_Type,
                     Min, Typ, Max, Unit, Source_Page, Notes.

    Returns:
        A complete Python script as a string, ready to be saved and executed.
    """
    # Build the constraint table as an embedded Python literal
    rows = []
    for c in constraints:
        rows.append(
            f'    {{"Signal_Class": {_q(c["Signal_Class"])}, '
            f'"Rule_Type": {_q(c["Rule_Type"])}, '
            f'"Min": {_q(c.get("Min"))}, '
            f'"Typ": {_q(c.get("Typ"))}, '
            f'"Max": {_q(c.get("Max"))}, '
            f'"Unit": {_q(c.get("Unit"))}, '
            f'"Source_Page": {_q(c.get("Source_Page"))}, '
            f'"Notes": {_q(c.get("Notes"))}}}'
        )
    constraints_literal = "[\n" + ",\n".join(rows) + "\n]" if rows else "[]"

    return f'''#!/usr/bin/env python
"""Xpedition CES — SI/PI Constraint Push Script
Auto-generated by the GDMS Space Hardware Assistant.

This script connects to a running Xpedition Designer instance via COM and
pushes SI/PI design constraints into the Constraint Editor System (CES).

Usage:
    1. Open the target design in Xpedition Designer.
    2. Run this script from a Python environment with pywin32 installed:
       python xpedition_ces_update.py
"""
import sys

# ---------------------------------------------------------------------------
# Constraint data (auto-generated from datasheet extraction)
# ---------------------------------------------------------------------------
CONSTRAINTS = {constraints_literal}

# Map Rule_Type to CES constraint categories
CES_CATEGORY_MAP = {{
    "Impedance": "Electrical.Impedance",
    "Propagation_Delay": "Timing.PropDelay",
    "Skew": "Timing.Skew",
    "Rise_Time": "Timing.RiseTime",
    "Fall_Time": "Timing.FallTime",
    "Voltage_Level": "Electrical.Voltage",
    "Spacing": "Physical.Spacing",
    "Max_Length": "Physical.MaxLength",
    "Differential_Pair": "Electrical.DiffPair",
    "Overshoot": "Electrical.Overshoot",
    "Undershoot": "Electrical.Undershoot",
    "Crosstalk": "Electrical.Crosstalk",
    "Other": "Electrical.Other",
}}


def main():
    try:
        import win32com.client
    except ImportError:
        print("ERROR: pywin32 is not installed.")
        print("Install it with:  pip install pywin32")
        sys.exit(1)

    print("GDMS Space Hardware Assistant — Xpedition CES Constraint Push Script")
    print(f"Total constraints to apply: {{len(CONSTRAINTS)}}")
    print("-" * 60)

    # --- Connect to Xpedition Designer ---
    try:
        vdapp = win32com.client.Dispatch("ViewDraw.Application")
        print("SUCCESS: Connected to Xpedition Designer (ViewDraw.Application)")
    except Exception as e:
        print(f"ERROR: Could not connect to Xpedition Designer: {{e}}")
        print("Make sure the application is running with a design open.")
        sys.exit(1)

    # --- Apply constraints to CES ---
    applied = 0
    skipped = 0
    for rule in CONSTRAINTS:
        signal_class = rule["Signal_Class"]
        rule_type = rule["Rule_Type"]
        ces_category = CES_CATEGORY_MAP.get(rule_type, "Electrical.Other")
        min_val = rule.get("Min")
        typ_val = rule.get("Typ")
        max_val = rule.get("Max")
        unit = rule.get("Unit", "")
        notes = rule.get("Notes", "")

        print(f"\\n  Signal Class: {{signal_class}}")
        print(f"    Rule: {{rule_type}} (CES: {{ces_category}})")
        print(f"    Min: {{min_val or '-'}}  Typ: {{typ_val or '-'}}  Max: {{max_val or '-'}}  Unit: {{unit or '-'}}")
        if notes:
            print(f"    Notes: {{notes}}")

        try:
            # TODO: Replace with actual Xpedition CES API calls.
            # Example pattern (project-specific):
            #   ces = vdapp.GetProjectData().GetConstraintEditor()
            #   net_class = ces.GetNetClass(signal_class)
            #   if not net_class:
            #       net_class = ces.CreateNetClass(signal_class)
            #   constraint = net_class.AddConstraint(ces_category)
            #   if min_val: constraint.SetMin(min_val)
            #   if typ_val: constraint.SetTyp(typ_val)
            #   if max_val: constraint.SetMax(max_val)
            print(f"    [STUB] Would set {{ces_category}} on class '{{signal_class}}'")
            applied += 1
        except Exception as e:
            print(f"    [SKIP] Failed to apply constraint: {{e}}")
            skipped += 1

    print("\\n" + "=" * 60)
    print(f"Done. Applied: {{applied}}, Skipped: {{skipped}}")


if __name__ == "__main__":
    main()
'''


def _q(value) -> str:
    """Quote a string for embedding in Python source, or return None literal."""
    if value is None:
        return "None"
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
