"""Pydantic schemas for the FPGA I/O Pin-Swap Bridge (Phase 2)."""
from typing import List, Optional

from pydantic import BaseModel, Field


class PinSwap(BaseModel):
    """Represents one pin that has moved to a new physical location."""

    Signal_Name: str = Field(description="Net / signal name shared between FPGA and schematic.")
    Old_Pin: str = Field(description="Pin identifier in the baseline (Xpedition) pinout.")
    New_Pin: str = Field(description="Pin identifier in the new (Vivado) pinout.")
    Old_Bank: str = Field(description="I/O bank in the baseline pinout.")
    New_Bank: str = Field(description="I/O bank in the new pinout.")
    AI_Risk_Assessment: Optional[str] = Field(
        default=None,
        description="SI/PI risk flag generated by the AI layer in Step 3.",
    )


class PinDeltaResponse(BaseModel):
    """Response envelope for the compare-fpga-pins endpoint."""

    total_swaps: int
    swapped_pins: List[PinSwap]
