"""Pydantic schemas for Phase 7 — Schematic DRC (Design Rule Check)."""
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class Severity(str, Enum):
    Error = "Error"
    Warning = "Warning"
    Info = "Info"


class ViolationCategory(str, Enum):
    Power = "Power"
    Decoupling = "Decoupling"
    Termination = "Termination"
    Interface = "Interface"
    Connectivity = "Connectivity"
    Naming = "Naming"
    SpaceCompliance = "SpaceCompliance"


class PinType(str, Enum):
    Input = "Input"
    Output = "Output"
    Bidirectional = "Bidirectional"
    Power = "Power"
    Ground = "Ground"
    Passive = "Passive"
    OpenCollector = "OpenCollector"
    OpenDrain = "OpenDrain"
    NC = "NC"
    Unknown = "Unknown"


# ---------------------------------------------------------------------------
# Netlist data model
# ---------------------------------------------------------------------------

class NetlistPin(BaseModel):
    """A single pin on a net or component."""
    ref_des: str = Field(description="Reference designator (e.g. U1)")
    pin_name: str = Field(default="", description="Symbolic pin name (e.g. VCC, CLK)")
    pin_number: str = Field(default="", description="Physical pin number")
    pin_type: PinType = Field(default=PinType.Unknown)


class NetlistNet(BaseModel):
    """A single net in the netlist."""
    name: str = Field(description="Net name")
    pins: List[NetlistPin] = Field(default_factory=list)


class NetlistComponent(BaseModel):
    """A component instance in the netlist."""
    ref_des: str = Field(description="Reference designator")
    part_number: str = Field(default="")
    value: str = Field(default="")
    pins: List[NetlistPin] = Field(default_factory=list)


class Netlist(BaseModel):
    """Full parsed netlist."""
    components: List[NetlistComponent] = Field(default_factory=list)
    nets: List[NetlistNet] = Field(default_factory=list)
    power_nets: List[str] = Field(default_factory=list)
    ground_nets: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# DRC results
# ---------------------------------------------------------------------------

class DRCViolation(BaseModel):
    """A single DRC finding."""
    rule_id: str = Field(description="Rule identifier (e.g. PWR-001)")
    severity: Severity = Field(default=Severity.Warning)
    category: ViolationCategory = Field(default=ViolationCategory.Connectivity)
    message: str = Field(default="")
    affected_nets: List[str] = Field(default_factory=list)
    affected_components: List[str] = Field(default_factory=list)
    recommendation: str = Field(default="")
    ai_generated: bool = Field(default=False, description="True if generated by AI checker")


class NetlistSummary(BaseModel):
    """Summary statistics for a parsed netlist."""
    component_count: int = 0
    net_count: int = 0
    power_net_count: int = 0
    ground_net_count: int = 0


class DRCReport(BaseModel):
    """Full DRC analysis report."""
    netlist_summary: NetlistSummary = Field(default_factory=NetlistSummary)
    violations: List[DRCViolation] = Field(default_factory=list)
    pass_count: int = 0
    warning_count: int = 0
    error_count: int = 0
    info_count: int = 0
    overall_status: str = Field(default="PASS", description="PASS, WARNING, or FAIL")


# ---------------------------------------------------------------------------
# AI checker schema
# ---------------------------------------------------------------------------

class AIViolationBatch(BaseModel):
    """Schema the LLM must return — a list of DRC violations."""
    violations: List[DRCViolation] = Field(default_factory=list)
